### ISSUE TITLE
My package isn't web supported because it depends on another package that is???

### ISSUE THREAD

**Issue by JCKodel** [dart-lang/pana#1215]
URL: https://pub.dev/packages/query_stack_firebase_authentication/score

It says is doesn't support Windows, Linux, MacOS and Web (although I'm currently using it on web without issues).

The reason is:

```
Package does not support platform `Web`.
Because:

package:query_stack_firebase_authentication/query_stack_firebase_authentication.dart that imports:
package:query_stack_firebase_authentication/src/authentication_query.dart that imports:
package:adaptive_dialog/adaptive_dialog.dart that imports:
package:adaptive_dialog/src/text_input_dialog/show_text_input_dialog.dart that imports:
package:adaptive_dialog/src/text_input_dialog/macos_text_input_dialog.dart that imports:
package:macos_ui/macos_ui.dart that declares support for platforms: macOS.
```

But `adaptive_dialog` currently supports all platforms!

So, my package being marked as android/ios only doesn't make any sense =\

**Comment by sigurdm** [comment]
What is the bug here?

Is it because adaptive_dialog is a flutter package we dont respect its [platforms](https://docs.flutter.dev/development/packages-and-plugins/developing-packages#plugin-platforms) declaration?

**Comment by isoos** [comment]
It is a top-level `platforms` in `package:adaptive_dialog`'s pubspec: https://pub.dev/packages/adaptive_dialog/pubspec

**Comment by sigurdm** [comment]
Yeah - but I wonder why we don't respect it...

**Comment by isoos** [comment]
An offline discussion revealed that the current platform detection is intentional on transient package-level declarations, only using them to restrict the set of supported platforms. There are two ways right now to fix this issue:
- `package:adaptive_dialog` may use platform-specific libraries, so they don't depend on single-platform ones.
- `package:query_stack_firebase_authentication` could also have a top-level platforms declaration that will be trusted when analyzing the package.

**Comment by JCKodel** [comment]
Thank you. I already made changes to top-level platforms.

Just learned about them by this comment, but it fixes the issue.
