### ISSUE TITLE
0/10 points: Provide a valid pubspec.yaml

### ISSUE THREAD

**Issue by myConsciousness** [dart-lang/pana#1281]
Hi,

I'm not sure when this started, but I'm getting the following validation error in pub.dev. The URL in error is valid and can be accessed, but is determined as invalid during pub.dev validation.

```
0/10 points: Provide a valid pubspec.yaml

 Documentation URL doesn't exist.
At the time of the analysis https://atprotodart.com/docs/packages/atproto was unreachable. Make sure that the website is reachable via [HEAD](https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/HEAD) requests.
```

**Comment by myConsciousness** [comment]
Hi @isoos!

I'm deploying this website automatically with GitHub Actions but have not changed the server configuration for many months now. This error should not have occurred until a few days ago.

I will also investigate if there has been any change in the service I use.

**Comment by isoos** [comment]
Got the core reason:
- `package:safe_url_check` requires that the redirect URL must be absolute (must have either http or https scheme): https://github.com/google/dart-neats/blob/master/safe_url_check/lib/safe_url_check.dart#L118
- the server redirects to a relative url `location: /docs/packages/atproto/`.

As that part of the code is roughly unchanged since the initial release of the package, I assume that the server started the redirect recently.

I believe that the package used that method, because the original standard required absolute URLs in the location header:
https://www.rfc-editor.org/rfc/rfc2616#section-14.30

However, there seems to be an updated RFC, which now allows relative URLs in the location:
https://www.rfc-editor.org/rfc/rfc7231#section-7.1.2

I think this is a bug in `package:safe_url_check` and we should fix it. Filed https://github.com/google/dart-neats/issues/228 and will create a fix for it soon.

**Comment by isoos** [comment]
I think we've deployed the `safe_url_check` fixes, and now `pub.dev` shows a clear report on this section.
