### ISSUE TITLE
pana can't recognize my enum's documentation

### ISSUE THREAD

**Issue by frknkrc44** [dart-lang/pana#1297]
I have fully documented my project, but pana (and pub.dev) says there are undocumented parts.

https://github.com/frknkrc44/easy_utils/blob/main/lib/src/navigation/page_route_type.dart

I already documented this enum (you can see it) but the pana output (same as pub.dev):
```
72 out of 73 API elements (98.6 %) have documentation comments.

Some symbols that are missing documentation: `PageRouteType`.
```

**Comment by isoos** [comment]
I think this is a bug. We most likely detect that the enum constructor is without documentation, and we should have just skipped on it: https://pub.dev/documentation/easy_utils/latest/easy_utils/PageRouteType/PageRouteType.html

**Comment by frknkrc44** [comment]
@isoos I can see my documentation when I used this link: https://pub.dev/documentation/easy_utils/latest/easy_utils/PageRouteType.html#DEFAULT_APP and it's interesting.

**Comment by isoos** [comment]
@frknkrc44: There are two different API symbols there: there is the `easy_utils.PageRouteType` which is an enum (which you have linked to), and the `easy_utils.PageRouteType.PageRouteType` which is the constructor of the enum (which I have linked to). The bug is that we were processing the names and their documentation status in a wrong way. There is a fix coming soon.
