### ISSUE TITLE
Incorrect penalty for SDK constraint

### ISSUE THREAD

**Issue by nshahan** [dart-lang/pana#542]
I'm not sure how widespread this is but a package that has an SDK constraint like `>=2.0.0-dev.12.0 <2.5.0` gets a penalty in the analysis that seems incorrect. Doesn't this include the latest SDK (2.3.2 at the time I'm writing this) within the range?

https://pub.dev/packages/dart_internal#-analysis-tab- is showing the error:

Support the latest stable Dart SDK in pubspec.yaml. (-20 points)
The SDK constraint in pubspec.yaml doesn't allow the latest stable Dart SDK release.

**Comment by isoos** [comment]
The current check is to match if the SDK constraint has an overlap with `'>=2.9999.0 <3.0.0'`. I think we could make it more configurable, maybe by detecting the current SDK version and increasing it with a minor version (e.g. if current SDK is `2.3.2`, we should check if the SDK constraints allows `2.4.0`)

**Comment by isoos** [comment]
On a second thought on the dynamic constraint use, I think we should not change the current behaviour, mostly because in general I think it is not a good idea to depend on a package that may not be useable after a few months with a new Dart SDK release. There are many valid reasons to publish a package with such constraints, but we are optimising for general consumption, and a penalty and visual warning is a good way to make users wary about such things. In this case the README also has a few warning signs, but still, I think we should keep the current behaviour, maybe update the message to make it better. @jonasfj wdyt?

**Comment by jonasfj** [comment]
The use-case for specifying that your package is not compatible a future version of Dart seems very limited. Does it make sense outside special cases like `dart_internal`?

For now I'm not alarmed by pana giving -20 points to a package which features :skull_and_crossbones: in the README.
Although one could argue we should give the package extra points for honesty :)

------
But maybe we should update the message to saying:

>Support future stable Dart 2 SDKs in pubspec.yaml. (-20 points)
The SDK constraint in pubspec.yaml doesn't allow future stable Dart 2.x SDK releases.

That would make it more obvious what we are grading.
