### ISSUE TITLE
pub.dev shows bad score on flutter plugins that implements web

### ISSUE THREAD

**Issue by DavBfr** [dart-lang/pana#587]
My plugin https://pub.dev/packages/printing had a score of about 93 to 97. And seeing the availability of Flutter 1.12, I updated it with the support for macOS desktop embedding as well as Flutter-Web plugin and the score dropped to 78 because of platform conflict detections. There are no incompatibilities: Flutter can do Web too, isn't it?

**Comment by isoos** [comment]
@DavBfr: thanks for reporting this. The issue happens because we have now two parallel platform-detection code, and while we are displaying the results from the latest, we haven't entirely removed the older one from scoring, and it wasn't updated to handle this yet. We'll remove the old one from scoring, and your package will get the score back once we'll deploy a new release with the bug fixed (probably early next week).
