### ISSUE TITLE
downgrade pedantic used for analysis

### ISSUE THREAD

**Issue by jonasfj** [dart-lang/pana#601]
Recent versions pedantic has `prefer_single_quotes`.

Some people have complained that this causes a lot of friction in the community...

Maybe pana should punish people for vanity lints like this.

For now, I propose that we downgrade to pedantic `1.8.0` and file a bug to resolve what we should do going forward.

Maybe `is:pedantic` is a tag packages can earn, and we only reduce score for lints matching effective dart.

**Comment by isoos** [comment]
We had similar opposition in the past for many different rules that "punished" packages not already using them. Some developers are more vocal about these things than others, some changes are harder to fix on a larger codebase. However, we have rule of thumb for such circumstances: if something is a reasonable default (or became a reasonable default), we want to encourage developers to implement/migrate packages that way. We did this for pubspec changes and code analysis too, with varying degree of severity and score penalty.

`pedantic` is part of the recommended defaults (e.g. part of `stagehand` and also on the dart.dev site). I think it is not our role to cherrypick rules just because some developers are vocal about it. Instead, I'd concentrate on the amount of penalty, which I agree to be too harsh on such a linter rule, and #598 was created to limit the effect of that. Now with `pana 0.13.3` published, the maximum penalty for all the linter rules (whether they are quotes or others) will be 25%.

I think that would be a better compromise on this issue than removing the pedantic rule on our own.

**Comment by jonasfj** [comment]
I'm only proposing a stop-gap measure here.

**Comment by isoos** [comment]
Also this: https://github.com/dart-lang/pana/issues/463

**Comment by isoos** [comment]
#602 enabled the control of this, and pub.dev is using 1.8.0 now.
