### ISSUE TITLE
Should notify user that no default top-level library was found

### ISSUE THREAD

**Issue by SwissCheese5** [dart-lang/pana#654]
https://pub.dev/packages/dartbase_admin

I just tried publishing my first dart-native package 
![image](https://user-images.githubusercontent.com/7407478/84592001-37319d00-ae4b-11ea-9543-b682e66fa55a.png)

It seems to be breaking because I have conditional imports here that do different things depending on the platform
https://github.com/SwissCheese5/Dartbase-Admin-SDK/tree/master/lib/platform

But I can't quite tell.

**Comment by sigurdm** [comment]
The problem is that pana looks for a library called `lib/$packageName.dart` to use as entrypoint for the platform analysis. In this case `lib/dartbase_admin.dart`. But there is only the library called `lib/dartbase.dart`.

Now pana assumes that all libraries in `lib/` (except those in `lib/src`) are entrypoints.

@isoos @jonasfj Should we somehow make a suggestion when 'lib/$packageName.dart' isn't found to clarify the situation?

**Comment by isoos** [comment]
> Should we somehow make a suggestion when 'lib/$packageName.dart' isn't found to clarify the situation?

I think this is a good feedback to the developer. The package layout page defines only the suggested default when there is only a single library, so it would be useful to expose the analysis reasoning when we have multiple ones. Especially if they cause platform restrictions.

> Most packages define a single library that users can import. In that case, its name should usually be the same as the name of the package [...]
> https://dart.dev/tools/pub/package-layout#public-libraries

**Comment by isoos** [comment]
I think this has been fixed since.
