### ISSUE TITLE
Exclude `http://localhost[:port]` from secure URL in readme logic

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/pana#743]
URL: https://pub.dev/packages/redux/score

![Screen Shot 2020-07-23 at 4 21 12 PM](https://user-images.githubusercontent.com/17034/88347839-9b743600-cd00-11ea-8e6e-18051c1af621.png)

I guess this might be a pana issue...

**Comment by isoos** [comment]
I'm unsure if we should enable `http://localhost:8080/` **links** in readme.

Instead of linking to the localhost via `[text](http://localhost:8080)`, authors should use a code block of the URL like ``` `http://localhost:8080\` ```. That way the reader can still copy-paste the link, but an accidental reader (or a search engine) won't click on it, navigating to a non-existent page.

Let's discuss, wdyt? /cc @jonasfj, @sigurdm, @mit-mit

**Comment by kevmoo** [comment]
Agree w/ your analysis here. Shouldn't be a link in the first place!

...let's not make things more complicated

**Comment by sigurdm** [comment]
> I'm unsure if we should enable http://localhost:8080/ links in readme.

Good points. I agree with not allowing (at least not encouraging) localhost links.
