### ISSUE TITLE
Packages cannot declare which platforms they support

### ISSUE THREAD

**Issue by timsneath** [dart-lang/pana#889]
With the advent of FFI, there are an increasing number of packages (not platform plugins) that contain only Dart code, but which are designed to work on only certain platforms. This will increase as we add more platforms and transition more code to adopt FFI, since it will be increasingly infeasible for a platform integration package to support the wide range of platforms that Dart itself supports. 

As an obvious example, the `win32` package by design only supports Windows, but it doesn't have any means to enumerate that. 
![image](https://user-images.githubusercontent.com/2319867/119699234-c9397800-be06-11eb-99b7-c3561d9b3099.png)

This leads to customer confusion. For example:
https://github.com/timsneath/filepicker_windows/issues/9#issuecomment-847857643
https://github.com/timsneath/win32/issues/166

One potential solution would be to have an entry in `pubspec.yaml` for `supported_platforms` which would override the detection logic built into `pana` and allow plugin authors to explicitly declare which platforms they choose to support.

**Comment by alann-maulana** [comment]
Finally found this issue. It happen when publishing a package meant for all Flutter platforms. 

Using native package [flutter_image_compress](https://pub.dev/packages/flutter_image_compress) for both `Android` and `iOS`, otherwise (`Web`, `MacOS`, `Windows` & `Linux`) is using pure Dart package [image_compression](https://pub.dev/packages/image_compression). 

So when [image_compression_flutter](https://pub.dev/packages/image_compression_flutter) published it only detects Android, iOS and Web platforms only.

**Comment by mit-mit** [comment]
This has landed, but we still need to get docs updated on https://dart.dev/tools/pub/pubspec

**Comment by jonasfj** [comment]
Missing documentation is fixed with https://github.com/dart-lang/pub/issues/3143

**Comment by sigurdm** [comment]
This is done!
