### ISSUE TITLE
license test failure for unknown reason

### ISSUE THREAD

**Issue by isoos** [dart-lang/pana#962]
```
test/license_utils_test.dart: Load licenses from directory [E]                                                                                                                         
  Expected: 'bsd_2_clause'
    Actual: 'bsd_3_clause'
     Which: is different.
            Expected: bsd_2_clause
              Actual: bsd_3_clause
                          ^
             Differ at offset 4
  
  package:test_api                   expect
  test/license_utils_test.dart 42:7  main.<fn>
```

/cc @bharat-biradar - any idea why this would be a failing test? We've permanently included the spdx files in the repository, so it should be deterministic, but not sure why it is failing.

**Comment by bharat-biradar** [comment]
@isoos I just ran the tests by pulling the code from master branch of pana, and all the tests were passing.
![image](https://user-images.githubusercontent.com/62872048/132865998-9344f0f1-01db-45e7-a63f-678705060ca7.png)

I suspect it is because the test files are being read in a different order from the directory as opposed to the list I had mentioned.
```dart
const licenseNames = [
      'agpl_v3',
      'agpl_v3',
      'apache_v2',
      'apache_v2',
      'bsd_2_clause',
      'bsd_2_clause_in_comments',
      'bsd_3_clause',
    ];
```
If all the files were not being read we would caught it in this line.

`expect(licenses.length, 7);`.
